### ISSUE TITLE
Investigate why command verifying NATS account set up is throwing an error (init-nats-stream-consumers.sh)

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#733]
The command we're trying to run

```
nats account info --user=${NATS_ADMIN_USERNAME} --password="${NATS_ADMIN_PASSWORD}" --server=${NATS_URL} --tlskey=${NATS_TLSKEY} --tlscert=${NATS_TLSCERT}
```

Throws an error, something to the effect of "EOF encountered"

This command doesn't really do anything other than verify for us that the account was set up successfully from `jetstream.conf`. 

The server is still able to recover the consumers and streams previously set up still because that's how it is configured to behave but this is problematic for adding a new consumer, for example, to be set up by `init-nats-stream-consumers.sh`.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/733?planning-poker) with ZenHub @divyamadala30

**Comment by divyamadala30** [comment]
The error while running `nats-stream-manager` could be because of the delay in setting up `nats-jetstream`. Now that consumers and streams are being properly restored, `nats-jetstream` is taking longer than usual. So `nats-stream-manager` is running even before NATS server is available to connect. 

Some possible fixes:
1. Start `nats-jetstream` before `nats-stream-manager` and the other services
2. Ensure `Depends on:` from docker-compose.yaml is reliable, if not look for alternatives.

Another error to reolve:

Entries from server log shared by Ben:
```
[1] 2022/07/13 14:29:35.914268 [DBG] 172.24.0.8:55002 - cid:92 - Client connection created
[1] 2022/07/13 14:29:35.915081 [DBG] 172.24.0.8:55002 - cid:92 - Starting TLS client connection handshake
[1] 2022/07/13 14:29:37.865354 [ERR] 172.24.0.8:55002 - cid:92 - TLS handshake error: EOF
[1] 2022/07/13 14:29:37.865534 [DBG] 172.24.0.8:55002 - cid:92 - Client connection closed: TLS Handshake Failure
```

Another possible explanation to these errors could be a TLS handshake issue. A possible solution is changing the URL from `nats://jetstream:4222` to `tls://jetstream:4222`
