### ISSUE TITLE
Fix sorting on patient view table

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#960]

**Comment by qu8n** [comment]
@ao508 TLDR update: this issue may potentially require a considerable amount of work. I confirmed this with Aaron who suggested that we aligned with the PMs on prioritization, which we can do tomorrow, before going further down this path.

**For more context:** 
Today, sorting is done by making a new GraphQL request to sort data on the server side and returning that sorted data. When making that request, we pass in a param to the `sort` property to let GraphQL know which field to sort by. 

Unfortunately, fields like "# Samples" are nested fields, and GraphQL doesn't support sorting by nested fields today, only the high-level fields. This is because GraphQL's querying of fields gets resolved top-down: higher-level fields get resolved before nested ones. 

One solution is we can query all the data then sort on the client side, but that might be computationally expensive especially as our dataset grows. I assume we'll need to write some sort of custom resolver to take care of sorted data requests.
